### PR TITLE
STOR-1406: Rebase to v1.6.6 for OCP 4.15

### PR DESCRIPTION
**Pull request by jsafrane**
Diff to upstream v1.6.6:
https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/compare/v1.6.6...jsafrane:rebase-v1.6.6

Full changelogs since the last rebase (1.5.1):
* 1.6: https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/blob/master/CHANGELOG/CHANGELOG-1.6.md
* 1.5: https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/blob/master/CHANGELOG/CHANGELOG-1.5.md

It all looks as fixes or small updates. These look interesting:
* now supports tier "zonal" with large band. small band is actively blocked (https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/588). Zonal tier is [this](https://cloud.google.com/filestore/docs/service-tiers).
* Add labels to backups created through the driver (https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/561)
* CMEK support now won't be checked in the CSI driver, trying to create basic or premium tier instances with cmek will result in invalid argument error from the Filestore API.
  high scale tier instance creation with IP reservation is now supported (https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/563)

cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/override ci/prow/verify-commits
!

**Comment by chao007** [comment]
Backup labels:
```
gcloud filestore backups describe snapshot-777dd6c7-1838-4c94-8972-efa9d45b3e8d --region=us-central1
capacityGb: '1024'
createTime: '2023-11-22T03:30:46.687736753Z'
downloadBytes: '2541320'
labels:
  storage_gke_io_created-by: filestore_csi_storage_gke_io
  storage_gke_io_created-for_csi_snapshot_name: snapshot-777dd6c7-1838-4c94-8972-efa9d45b3e8d
name: projects/openshift-qe/locations/us-central1/backups/snapshot-777dd6c7-1838-4c94-8972-efa9d45b3e8d
sourceFileShare: vol1
sourceInstance: projects/openshift-qe/locations/us-central1-b/instances/pvc-907ceaf6-98aa-4f0d-a17f-976132e249bd
sourceInstanceTier: STANDARD
state: READY
storageBytes: '2473600'
```

**Pull request merged**
