### PR TITLE
STOR-1572: Rebase to upstream v1.6.11

### PR DESCRIPTION
**Pull request by tsmetana**
https://issues.redhat.com/browse/STOR-1572

Upstream Changelog:
https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/blob/master/CHANGELOG/CHANGELOG-1.6.md

Diff to upstream:
https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/compare/v1.6.11...tsmetana:gcp-filestore-csi-driver:rebase-1.6.11?expand=1

### CODE REVIEW

**Comment by tsmetana** [comment]
Rebased to include changes from PR #30.

**Comment by jsafrane** [comment]
/lgtm
@tsmetana please include link to upstream changelog in the PR description, so QE can check what's new (just bugfixes)

**Pull request merged**
